application:    vino-team
version:        2
runtime:        php55
api_version:    1

handlers:
        - url: /favicon\.ico
          static_files: public/favicon.ico
          upload: public/favicon\.ico

        - url: /build
          static_dir: public/build
          application_readable: true

        - url: /css
          static_dir: public/css

        - url: /emails
          static_dir: public/emails

        - url: /files
          static_dir: public/files

        - url: /fonts
          static_dir: public/fonts

        - url: /images
          static_dir: public/images

        - url: /js
          static_dir: public/js

        - url: /uploads
          static_dir: public/uploads

        - url: /.*
          script: public/index.php
          secure: always

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\.(?!env).*$
        - ^(.*/)?node_modules.*$
        - ^(.*/)?_ide_helper\.php$
        - ^(.*/)?\.DS_Store$

env_variables:
        GAE_SKIP_GCS_INIT: true
